/* End-to-end request import, controlled evidence, reduction, retest and proof. */
const fs=require('fs'),path=require('path'),assert=require('assert'),{spawn,spawnSync}=require('child_process');
const work=path.resolve(__dirname,'..'),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const out=path.resolve(process.env.AUTHZ_BROWSER_ASSESSMENT_ARTIFACTS||path.join(work,'artifacts/browser-assessments'));
fs.mkdirSync(out,{recursive:true});fs.rmSync(path.join(out,'acceptance.json'),{force:true});const temp=fs.mkdtempSync('/tmp/authzledger-assessment-browser-');let server,browser;
const fixture=String.raw`
import json,sys,threading,time
from pathlib import Path
from http.server import BaseHTTPRequestHandler,ThreadingHTTPServer
from authzledger.studio import StudioServer
root=Path(sys.argv[1]); requests=[]; objects={}; count=0
class Fixture(BaseHTTPRequestHandler):
 def log_message(self,*args):pass
 def send(self,status,body):
  raw=json.dumps(body).encode();self.send_response(status);self.send_header('Content-Length',str(len(raw)));self.end_headers();self.wfile.write(raw)
 def do_GET(self):
  requests.append(self.path);(root/'hits.json').write_text(json.dumps(requests))
  if self.path=='/me' and (root/'hold-me').exists():
   (root/'me-entered').write_text('entered')
   while (root/'hold-me').exists():time.sleep(.01)
  if self.path=='/me':return self.send(200,{'principal':'peer'})
  if self.path=='/known-denial':return self.send(403,{'error':'denied'})
  if self.path.startswith('/jobs/'):
   oid=self.path.split('/')[2];return self.send(200,{'id':oid,'state':objects.get(oid,'unknown')})
  owner=self.headers.get('Authorization')=='Bearer fixture-7dc24a91e6b84350a159cf2900ce6842'
  return self.send(200 if owner else 403,{'marker':'synthetic-A'} if owner or not (root/'fixed').exists() else {'error':'denied'})
 def do_POST(self):
  global count
  requests.append(self.path)
  if self.path=='/jobs':
   count+=1;oid='fixture-'+str(count);objects[oid]='draft';return self.send(201,{'id':oid})
  oid=self.path.split('/')[2]
  if not (root/'workflow-fixed').exists():objects[oid]='completed'
  self.send(200,{'ok':True})
 def do_DELETE(self):
  requests.append(self.path);objects.pop(self.path.split('/')[2],None);self.send(204,{})
f=ThreadingHTTPServer(('127.0.0.1',0),Fixture);threading.Thread(target=f.serve_forever,daemon=True).start()
s=StudioServer();print(json.dumps({'url':s.url,'target':'http://127.0.0.1:'+str(f.server_port)}),flush=True)
try:s.serve_forever()
finally:s.server_close();f.shutdown();f.server_close()
`;
(async()=>{
 server=spawn(process.env.PYTHON||'python3',['-u','-c',fixture,temp],{cwd:work});let stderr='';server.stderr.on('data',d=>stderr+=d);
 const fixtureInfo=await new Promise((resolve,reject)=>{let text='';server.stdout.on('data',d=>{text+=d;try{resolve(JSON.parse(text.trim()));}catch{}});server.on('exit',code=>reject(Error('Fixture exited '+code+stderr)));setTimeout(()=>reject(Error('Fixture timeout '+stderr)),10000).unref();});
 browser=await chromium.launch({headless:true,...(process.env.CHROME_EXECUTABLE?{executablePath:process.env.CHROME_EXECUTABLE}:{})});const context=await browser.newContext({viewport:{width:1536,height:1060},acceptDownloads:true});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));async function tabTo(selector){const node=page.locator(selector).first();await node.waitFor({state:'visible'});for(let index=0;index<350;index++){if(await node.evaluate(el=>el===document.activeElement))return node;await page.keyboard.press('Tab');}throw Error('Keyboard target is not reachable: '+selector);}
 async function activate(selector){await tabTo(selector);await page.keyboard.press('Enter');}
 async function typeText(selector,value){await tabTo(selector);await page.keyboard.press('Control+a');await page.keyboard.insertText(value);}
 async function selectValue(selector,value){const node=await tabTo(selector);const index=await node.evaluate((el,value)=>[...el.options].findIndex(option=>option.value===value),value);assert(index>=0,'Missing option '+value);await page.keyboard.press('Home');for(let count=0;count<index;count++)await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');}
 async function check(selector){const node=await tabTo(selector);if(!await node.isChecked())await page.keyboard.press('Space');}
 await page.goto(fixtureInfo.url);await page.locator('#access-matrix .matrix-cell').nth(23).waitFor();await activate('.nav[data-panel="assessment"]');
 await page.keyboard.press('Control+k');await typeText('#a-command-search','contrast');await page.keyboard.press('Enter');await page.locator('#a-contrast.active').waitFor();await page.keyboard.press('Control+k');await page.keyboard.press('Escape');assert.equal(await page.locator('#a-palette').evaluate(n=>n.open),false);
 await activate('[data-step="import"]');await selectValue('#a-profile','har-1.2');const har={log:{version:'1.2',entries:[{request:{method:'GET',url:fixtureInfo.target+'/invoice/A',headers:[{name:'Authorization',value:'Bearer imported-secret'},{name:'Accept',value:'application/json'}]},response:{status:403}}]}};
 await page.locator('#a-import-file').setInputFiles({name:'request.har',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(har))});await activate('#a-import-entries button');await typeText('#a-rule-pointer','/marker');await typeText('#a-rule-value','synthetic-A');await typeText('#a-negative-path','/known-denial');await typeText('#a-owner-secret','Bearer fixture-7dc24a91e6b84350a159cf2900ce6842');await typeText('#a-actor-secret','Bearer fixture-30ea81cd7f264eeea0ac99dd59dfa0b2');await activate('#a-preview');await page.locator('#a-plan-card:not([hidden])').waitFor();assert.match(await page.locator('#a-plan-budget').innerText(),/4 request/);assert.equal(await page.locator('#a-owner-secret').inputValue(),'');assert.equal(await page.locator('#a-actor-secret').inputValue(),'');
 async function run(){await page.locator('#a-plan-card:not([hidden])').waitFor();const retainedCount=await page.evaluate(()=>assessment.executions.length+assessment.traceIds.length);await check('#a-authorized');const dispatched=page.waitForResponse(r=>r.url().endsWith('/api/assessment/run'));await activate('#a-run');const job=await (await dispatched).json();assert(job.id,'Reviewed execution must return a job');await page.waitForFunction(count=>!assessment.job&&assessment.executions.length+assessment.traceIds.length>count&&document.getElementById('a-job-state').textContent.startsWith('Execution complete'),retainedCount,{timeout:20000});assert.equal((await page.evaluate(id=>api('/api/jobs/'+id),job.id)).state,'complete');}
 fs.writeFileSync(path.join(temp,'hold-me'),'hold');let pollDropped;const dropped=new Promise(resolve=>pollDropped=resolve);let interrupted=false;await page.route('**/api/jobs/*',async route=>{if(!interrupted){const response=await route.fetch();const observed=await response.json();assert.equal(observed.state,'running');interrupted=true;await route.abort('failed');pollDropped(observed.id);}else await route.continue();});await check('#a-authorized');await activate('#a-run');const interruptedJob=await dropped;await page.locator('#a-reconnect:not([hidden])').waitFor();assert.equal(await page.evaluate(()=>assessment.job),interruptedJob);assert.equal((await page.evaluate(id=>api('/api/jobs/'+id),interruptedJob)).state,'running');assert.equal(await page.locator('#a-run').isEnabled(),false);fs.unlinkSync(path.join(temp,'hold-me'));await activate('#a-reconnect');await page.waitForFunction(()=>assessment.current?.value.findings[0]?.status==='confirmed'&&!assessment.job);await page.unroute('**/api/jobs/*');assert.equal(JSON.parse(fs.readFileSync(path.join(temp,'hits.json'),'utf8')).length,4);assert.equal(await page.evaluate(async()=>(await api('/api/session')).assessment_jobs.length),1);
 await activate('#a-findings button');await page.waitForFunction(()=>document.getElementById('a-inspector-fields').textContent.includes('violation · confirmed'));assert.match(await page.locator('#a-inspector-fields').innerText(),/violation.*confirmed/);await activate('#a-view-graph');await activate('#a-graph button');assert.match(await page.locator('#a-inspector-fields').innerText(),/protected-content-boundary|Rule/);await page.screenshot({path:path.join(out,'contrast-inspector.png'),fullPage:true});
 await activate('.nav[data-panel="history"]');await activate('#history-refresh');await page.locator('.timeline-run').first().waitFor();await activate('.timeline-run');await activate('.nav[data-panel="assessment"]');assert.match(await page.locator('#a-inspector-fields').innerText(),/violation.*confirmed/);
 assert.equal(await page.evaluate(()=>JSON.stringify(sessionStorage)+JSON.stringify(localStorage)),'{}{}');assert.equal((await page.content()).includes('imported-secret'),false);
 await activate('#a-reduce-open');await page.locator('#a-reduction-units input').first().waitFor();await activate('#a-reduction-preview');await run();await page.locator('#a-reduction-result .assessment-trace').waitFor();assert.match(await page.locator('#a-reduction-result').innerText(),/accepted removals/);
 fs.writeFileSync(path.join(temp,'fixed'),'fixed');await activate('[data-step="investigate"]');await activate('#a-retest');await page.locator('#a-plan-card:not([hidden])').waitFor();await run();assert.match(await page.locator('#a-retest-result').innerText(),/fix_verified/);
 await activate('[data-step="workflow"]');await activate('#a-workflow-preview');await page.locator('#a-plan-card:not([hidden])').waitFor();await run();await page.locator('#a-workflow-result .assessment-trace').waitFor();assert.match(await page.locator('#a-workflow-result').innerText(),/violation/);
 fs.writeFileSync(path.join(temp,'workflow-fixed'),'fixed');await activate('#a-workflow-assurance-options summary');await typeText('#a-workflow-cycles','2');await typeText('#a-workflow-budget','12');await activate('#a-workflow-preview');await page.locator('#a-plan-card:not([hidden])').waitFor();assert.match(await page.locator('#a-plan-rows').innerText(),/2 maximum cycles.*Session-only history/);await run();assert.match(await page.locator('#a-workflow-result').innerText(),/2 completed cycles/);assert.equal(await page.locator('#a-workflow-result').evaluate(n=>(n.textContent.match(/cleanup complete/g)||[]).length),2);fs.unlinkSync(path.join(temp,'workflow-fixed'));await activate('#a-workflow-preview');await run();assert.match(await page.locator('#a-workflow-result').innerText(),/violation/);assert.match(await page.locator('#a-workflow-result').innerText(),/1 completed cycles/);
 await activate('[data-step="handover"]');await typeText('#a-reviewer','Browser acceptance fixture');await typeText('#a-summary','A 403 response leaked a synthetic protected marker. Fresh controls verified the fix.');await activate('#a-handover details summary');await typeText('#a-impact','Protected synthetic tenant marker disclosed in a 403 response.');await typeText('#a-remediation','Apply resource authorization before serializing protected fields.');await selectValue('#a-standard','API|2023|API1:2023');await typeText('#a-standard-rationale','Cross-tenant object access was evaluated with three independent controls.');await activate('#a-annotation-save');await activate('#a-freeze');await page.locator('#a-json:enabled').waitFor();
 for(const format of ['json','html','pdf']){const pending=page.waitForEvent('download');await activate('#a-'+format);const download=await pending;await download.saveAs(path.join(out,'assessment.'+format));}
 let pending=page.waitForEvent('download');await activate('#a-signing');let download=await pending;await download.saveAs(path.join(out,'verification-key.pem'));pending=page.waitForEvent('download');await activate('#a-proof');download=await pending;await download.saveAs(path.join(out,'proof.zip'));
 const verified=spawnSync(process.env.PYTHON||'python3',['-c',`import zipfile,sys,subprocess\nfrom pathlib import Path\np=Path(sys.argv[1]);zipfile.ZipFile(p/'proof.zip').extractall(p/'proof')\nr=subprocess.run([sys.executable,'-I','tools/verify_bundle.py',str(p/'proof'),'--public-key',str(p/'verification-key.pem')],capture_output=True,text=True)\nprint(r.stdout,r.stderr);raise SystemExit(r.returncode)`,out],{cwd:work,encoding:'utf8'});assert.equal(verified.status,0,verified.stdout+verified.stderr);
 await page.screenshot({path:path.join(out,'signed-handover.png'),fullPage:true});
 await activate('[data-step="contrast"]');let releasePreview;const holdPreview=new Promise(resolve=>releasePreview=resolve);let previewReady;const requestedPreview=new Promise(resolve=>previewReady=resolve);await page.route('**/api/assessment/plan',async route=>{const response=await route.fetch();previewReady();await holdPreview;await route.fulfill({response});});await activate('#a-preview');await requestedPreview;await typeText('#a-title','Changed while preview was pending');releasePreview();await page.waitForFunction(()=>document.getElementById('notice').textContent.includes('draft changed'));assert.equal(await page.locator('#a-run').isEnabled(),false);await page.unroute('**/api/assessment/plan');
 const retained=await page.evaluate(async()=>({session:await api('/api/session'),digest:assessment.current.value.execution_digest}));const resumedJob=retained.session.assessment_jobs.filter(job=>job.kind==='experiment').at(-1).id;await page.reload();await page.waitForFunction(()=>document.getElementById('session').textContent==='Session unavailable');await page.goto(fixtureInfo.url);await page.locator('#a-recovery button').first().waitFor({state:'attached'});await activate('.nav[data-panel="assessment"]');await activate('#a-recovery button[data-job-id="'+resumedJob+'"]');await page.waitForFunction(digest=>assessment.current?.value.execution_digest===digest,retained.digest);assert.equal(await page.evaluate(async()=>(await api('/api/session')).assessment_jobs.length),retained.session.assessment_jobs.length);

 const performanceResult=await page.evaluate(async()=>{const target=assessment.current.value.contract.target;const contract={version:1,name:'1000-boundary UI benchmark',target,identities:{reader:{headers:{}}},limits:{max_requests:1000},cases:Array.from({length:1000},(_,index)=>({id:'boundary-'+index,identity:'reader',method:'GET',path:'/synthetic/'+index,expect:{status:[403]}}))};const data=await api('/api/graph',{contract});panel('intelligence');setGraph(data.graph);const latencies=[],input=[];for(let iteration=0;iteration<20;iteration++){const start=performance.now();document.getElementById('graph-filter').value=iteration%2?'boundary-99':'boundary-';document.getElementById('graph-filter').dispatchEvent(new Event('input'));input.push(performance.now()-start);document.querySelector('#graph-edges button')?.click();await new Promise(resolve=>requestAnimationFrame(resolve));latencies.push(performance.now()-start);}const percentile=values=>[...values].sort((a,b)=>a-b)[Math.ceil(values.length*.95)-1];return {case_count:1000,rendered_bound:100,interactions:20,selection_filter_p95_ms:percentile(latencies),input_feedback_p95_ms:percentile(input),measured_user_agent:navigator.userAgent,logical_cpus:navigator.hardwareConcurrency,network_included:false};});assert(performanceResult.selection_filter_p95_ms<=250,JSON.stringify(performanceResult));assert(performanceResult.input_feedback_p95_ms<=100,JSON.stringify(performanceResult));fs.writeFileSync(path.join(out,'performance.json'),JSON.stringify(performanceResult,null,2));
 await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'acceptance.json'),JSON.stringify({passed:true,keyboard_only:true,file_picker_fixture_injection:true,workflows:['offline HAR import','credential binding without browser persistence','keyboard command palette','polling failure during held running control and same-job reconnection','403 marker with valid controls','shared matrix / graph / history context','stale preview revision rejection','reopen original session and reconnect without redispatch','minimal reproducer','source-bound fix retest','fresh workflow and cleanup','bounded two-cycle workflow assurance and stop after violation','frozen JSON / HTML / PDF','fresh local signing key','independent offline proof verification','390px viewport'],page_errors:errors},null,2));console.log('Assessment browser acceptance passed.');
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();if(server)server.kill('SIGTERM');});
