const fs=require('fs'),path=require('path'),assert=require('assert'),{spawn,spawnSync}=require('child_process');
const work=path.resolve(__dirname,'..'),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const out=path.resolve(process.env.AUTHZ_BROWSER_V1_ARTIFACTS||path.join(work,'artifacts/browser-v1'));
fs.mkdirSync(out,{recursive:true});
const temporary=fs.mkdtempSync('/tmp/authzledger-browser-v1-'),privateKey=path.join(temporary,'private.pem'),publicKey=path.join(temporary,'public.pem');
let server,browser;
async function download(page,id,name){const waiting=page.waitForEvent('download');await page.locator(id).click();const file=await waiting;await file.saveAs(path.join(out,name));return fs.readFileSync(path.join(out,name));}
(async()=>{
 const keygen=spawnSync(process.env.PYTHON||'python3',['-c','from authzledger.signing import generate_keypair; import sys; generate_keypair(sys.argv[1],sys.argv[2])',privateKey,publicKey],{cwd:work,encoding:'utf8'});assert.equal(keygen.status,0,keygen.stderr);
 server=spawn(process.env.PYTHON||'python3',['-u','-m','authzledger','studio','--history',path.join(temporary,'history.sqlite3'),'--signing-key',privateKey,'--public-key',publicKey],{cwd:work});
 const url=await new Promise((resolve,reject)=>{let text='';server.stdout.on('data',chunk=>{text+=chunk;const match=text.match(/http:\/\/127\.0\.0\.1:\d+\/#[A-Za-z0-9_-]+/);if(match)resolve(match[0]);});server.on('error',reject);setTimeout(()=>reject(Error('Studio startup timeout')),10000).unref();});
 browser=await chromium.launch({headless:true,...(process.env.CHROME_EXECUTABLE?{executablePath:process.env.CHROME_EXECUTABLE}:{})});
 const context=await browser.newContext({viewport:{width:1600,height:1050},acceptDownloads:true,recordVideo:{dir:out,size:{width:1600,height:1050}}});
 const page=await context.newPage(),errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto(url);await page.locator('#access-matrix .matrix-cell').nth(23).waitFor();
 await page.locator('.nav[data-panel="intelligence"]').click();await page.locator('#map-build').click();await page.locator('#graph-edges .graph-row').nth(23).waitFor();
 assert.equal(await page.locator('#graph-edges .graph-row').count(),24);assert.match(await page.locator('#graph-counts').innerText(),/0\s*independent policy decisions/);
 assert.equal(await page.locator('#proof-export').isEnabled(),false);
 await page.locator('#graph-pin').click();await page.locator('.policy-editor summary').click();
 const policy={schema_version:1,engine:'local',default:'deny',rules:[{id:'allow-own-invoice',effect:'allow',identities:['north_member'],methods:['GET'],paths:['/invoice/invoice-a']}]};
 await page.locator('#independent-policy').fill(JSON.stringify(policy,null,2));await page.locator('#policy-evaluate').click();
 await page.waitForFunction(()=>document.getElementById('policy-status').textContent.startsWith('Active local policy'));
 assert.match(await page.locator('#graph-counts').innerText(),/24\s*independent policy decisions/);assert.match(await page.locator('#graph-differences').innerText(),/24\s+Policy drift/);
 await page.locator('.policy-editor').screenshot({path:path.join(out,'policy.png')});await page.locator('.graph-changes').screenshot({path:path.join(out,'drift.png')});
 await page.locator('#policy-clear').click();await page.waitForFunction(()=>document.getElementById('policy-status').textContent.startsWith('No independent policy is active'));
 await page.locator('.nav[data-panel="workspace"]').click();await page.locator('#demo').click();await page.waitForFunction(()=>document.getElementById('run-state').textContent.startsWith('Local demonstration complete'),{},{timeout:30000});
 await page.locator('.results-card').screenshot({path:path.join(out,'evidence.png')});
 await page.locator('.nav[data-panel="history"]').click();await page.locator('.timeline-run').nth(1).waitFor();assert.equal(await page.locator('.timeline-run').count(),2);assert.match(await page.locator('#history-storage').innerText(),/Persistent local history/);
 await page.locator('.timeline-run').first().click();await page.locator('#history-open').waitFor({state:'visible'});await page.locator('#history').screenshot({path:path.join(out,'history.png')});
 await page.locator('#history-open').click();await page.locator('#graph-edges .graph-row').nth(5).waitFor();assert.equal(await page.locator('#graph-edges .graph-row').count(),6);
 assert.match(await page.locator('#graph-counts').innerText(),/6\s*observed decisions/);await page.locator('#graph-reason').click();await page.waitForFunction(()=>document.getElementById('reasoning-notes').textContent.includes('Deterministic explanation'));
 assert.equal(await page.locator('#use-local-model').isEnabled(),false);
 await page.locator('#notice').evaluate(el=>el.hidden=true);await page.locator('.intelligence-layout').screenshot({path:path.join(out,'graph.png')});await page.locator('.graph-inspector').screenshot({path:path.join(out,'reasoning.png')});
 const demoPolicy={schema_version:1,engine:'local',default:'deny',rules:[{id:'owner-invoice',effect:'allow',identities:['owner'],paths:['/invoices/owner-1']},{id:'peer-invoice',effect:'allow',identities:['peer'],paths:['/invoices/peer-1']},{id:'admin-audit',effect:'allow',identities:['admin'],paths:['/admin/audit']}]};
 await page.locator('.nav[data-panel="history"]').click();await page.locator('.timeline-run').nth(1).click();await page.waitForFunction(()=>document.getElementById('history-detail').textContent.includes('6 configured checks'));await page.locator('#history-open').click();
 if(!await page.locator('.policy-editor').evaluate(el=>el.open))await page.locator('.policy-editor summary').click();
 await page.locator('#independent-policy').fill(JSON.stringify(demoPolicy,null,2));await page.locator('#policy-evaluate').click();await page.waitForFunction(()=>document.getElementById('graph-counts').textContent.includes('6independent policy decisions'));
 await page.locator('.graph-boundary').filter({hasText:/^peer → GET \/invoices\/owner-1$/}).click();await page.locator('#notice').evaluate(el=>el.hidden=true);await page.locator('.intelligence-layout').screenshot({path:path.join(out,'graph-before.png')});await page.locator('#graph-pin').click();
 await page.locator('.nav[data-panel="history"]').click();await page.locator('.timeline-run').first().click();await page.locator('#history-open').click();await page.locator('#policy-evaluate').click();await page.waitForFunction(()=>document.getElementById('graph-counts').textContent.includes('6independent policy decisions'));await page.waitForFunction(()=>document.getElementById('graph-differences').textContent.includes('2Resolved findings'));
 await page.locator('.graph-boundary').filter({hasText:/^peer → GET \/invoices\/owner-1$/}).click();await page.locator('#notice').evaluate(el=>el.hidden=true);await page.locator('.intelligence-layout').screenshot({path:path.join(out,'graph-after.png')});await page.locator('.graph-changes').screenshot({path:path.join(out,'diff-demo.png')});await page.locator('.instant-proof').screenshot({path:path.join(out,'proof.png')});
 const proof=await download(page,'#proof-export','authzledger-proof.zip');assert.equal(proof.readUInt16LE(0),0x4b50);assert(!proof.includes(Buffer.from('PRIVATE KEY')));
 await page.locator('.nav[data-panel="history"]').click();await page.locator('#history-retest').click();await page.waitForFunction(()=>document.getElementById('plan').textContent.includes('6 explicit requests'));assert.match(await page.locator('#plan').innerText(),/6 explicit requests/);assert.equal(await page.locator('#run').isEnabled(),false);
 assert.match(await page.locator('#notice').innerText(),/Retest prepared/);
 await page.locator('.nav[data-panel="intelligence"]').click();await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:path.join(out,'mobile-graph.png'),fullPage:true});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);if(overflow)console.log(await page.evaluate(()=>({size:{width:innerWidth,doc:document.documentElement.scrollWidth,body:document.body.scrollWidth,nav:document.querySelector('nav').getBoundingClientRect().toJSON()},elements:[...document.querySelectorAll('body *')].map(el=>({name:el.tagName,id:el.id,cls:el.className,right:Math.round(el.getBoundingClientRect().right),width:Math.round(el.getBoundingClientRect().width)})).filter(el=>el.right>innerWidth+1).slice(0,40)})));assert(!overflow,'Intelligence page must not overflow the mobile viewport.');await page.screenshot({path:path.join(out,'mobile-graph.png'),fullPage:true});
 assert.deepEqual(errors,[]);const result={passed:true,browser:await browser.version(),page_errors:errors,workflows:['three-layer contract graph with explicit missing policy/evidence','independent local policy evaluation','separate policy drift','real before/after demo','persistent integer-ID history','deterministic evidence explanation','AI disabled without local startup configuration','signed graph and report ZIP export','controlled retest requires scope authorization','390px intelligence viewport without page overflow']};
 fs.writeFileSync(path.join(out,'acceptance.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result));
 await context.close();await browser.close();server.kill();fs.rmSync(temporary,{recursive:true,force:true});
})().catch(async error=>{console.error(error);if(browser)await browser.close();if(server)server.kill();fs.rmSync(temporary,{recursive:true,force:true});process.exit(1)});
