/* Actual-browser negative corpus: hostile source text, credential canaries and CSP. */
const fs=require('fs'),path=require('path'),assert=require('assert'),{spawn,spawnSync}=require('child_process');
const work=path.resolve(__dirname,'..'),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const out=path.resolve(process.env.AUTHZ_BROWSER_SECURITY_ARTIFACTS||path.join(work,'artifacts/browser-assessment-security'));
fs.mkdirSync(out,{recursive:true});const temp=fs.mkdtempSync('/tmp/authzledger-browser-security-');let server,browser;
const canaries={header:'AUTHZ_CANARY_HEADER_628491',cookie:'AUTHZ_CANARY_COOKIE_739512',query:'AUTHZ_CANARY_QUERY_840623',body:'AUTHZ_CANARY_BODY_951734',response:'AUTHZ_CANARY_RESPONSE_062845',error:'AUTHZ_CANARY_ERROR_173956',owner:'AUTHZ_CANARY_OWNER_284067',peer:'AUTHZ_CANARY_PEER_395178'};
const hostile='<img src=x onerror="window.__authzXss=1">';
const fixture=String.raw`
import json,sys,threading
from pathlib import Path
from http.server import BaseHTTPRequestHandler,ThreadingHTTPServer
from authzledger.studio import StudioServer
root=Path(sys.argv[1]);hits=[]
class Fixture(BaseHTTPRequestHandler):
 def log_message(self,*args):pass
 def do_GET(self):
  hits.append(self.path);(root/'hits.json').write_text(json.dumps(hits))
  if self.path=='/me':status,body=200,{'principal':'peer'}
  elif self.path=='/known-denial':status,body=403,{'error':'AUTHZ_CANARY_ERROR_173956'}
  else:status,body=(200 if self.headers.get('Authorization')=='Bearer AUTHZ_CANARY_OWNER_284067' else 403),{'marker':'synthetic-A','error':'AUTHZ_CANARY_RESPONSE_062845','untrusted':'<img src=x onerror="window.__authzXss=1">'}
  raw=json.dumps(body).encode();self.send_response(status);self.send_header('Content-Length',str(len(raw)));self.end_headers();self.wfile.write(raw)
f=ThreadingHTTPServer(('127.0.0.1',0),Fixture);threading.Thread(target=f.serve_forever,daemon=True).start()
s=StudioServer(history_path=root/'history.sqlite');print(json.dumps({'url':s.url,'target':'http://127.0.0.1:'+str(f.server_port)}),flush=True)
try:s.serve_forever()
finally:s.server_close();f.shutdown();f.server_close()
`;
function noCanaries(value,label){const text=typeof value==='string'?value:JSON.stringify(value);for(const secret of Object.values(canaries))assert(!text.includes(secret),label+' leaked a credential canary');}
function hits(){return fs.existsSync(path.join(temp,'hits.json'))?JSON.parse(fs.readFileSync(path.join(temp,'hits.json'),'utf8')):[];}
(async()=>{
 server=spawn(process.env.PYTHON||'python3',['-u','-c',fixture,temp],{cwd:work});let stderr='',stdout='';server.stderr.on('data',data=>stderr+=data);
 const info=await new Promise((resolve,reject)=>{server.stdout.on('data',data=>{stdout+=data;try{resolve(JSON.parse(stdout.trim()));}catch{}});server.on('exit',code=>reject(Error('Fixture exited '+code+' '+stderr)));setTimeout(()=>reject(Error('Fixture timeout '+stderr)),10000).unref();});
 browser=await chromium.launch({headless:true,...(process.env.CHROME_EXECUTABLE?{executablePath:process.env.CHROME_EXECUTABLE}:{})});const context=await browser.newContext({viewport:{width:1400,height:1000},acceptDownloads:true});const page=await context.newPage(),errors=[],apiResponses=[];page.on('pageerror',error=>errors.push(error.message));page.on('response',async response=>{if(response.url().includes('/api/')){try{apiResponses.push(await response.text());}catch{}}});
 const navigation=await page.goto(info.url);assert.match(navigation.headers()['content-security-policy'],/script-src 'self'/);assert.match(navigation.headers()['content-security-policy'],/default-src 'none'/);await page.locator('#access-matrix .matrix-cell').nth(23).waitFor();await page.locator('.nav[data-panel="assessment"]').click();await page.locator('#a-profile').selectOption('har-1.2');
 const maliciousHar={log:{version:'1.2',entries:[{comment:hostile,request:{method:'POST',url:info.target+'/payload/<svg/onload=window.__authzXss=1>?access_token='+canaries.query,headers:[{name:'Authorization',value:'Bearer '+canaries.header},{name:'Cookie',value:'sid='+canaries.cookie}],postData:{mimeType:'application/json',text:JSON.stringify({password:canaries.body,note:hostile})}},response:{status:403,content:{mimeType:'application/json',text:JSON.stringify({password:canaries.response,error:canaries.error,markup:hostile})}}}]}};
 const importedResponse=page.waitForResponse(response=>response.url().endsWith('/api/assessment/import'));await page.locator('#a-import-file').setInputFiles({name:'hostile-source.har',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(maliciousHar))});const imported=await (await importedResponse).json();assert.equal(imported.import.entries.length,1);const entry=imported.import.entries[0];assert(entry.execution_blockers.length>0);assert(entry.secret_slots.some(slot=>slot.kind==='credential_query'));assert(entry.secret_slots.some(slot=>slot.kind==='credential_json'));noCanaries(imported,'import response');noCanaries(await page.content(),'rendered source');assert.equal(await page.evaluate(()=>window.__authzXss),undefined);assert.equal(await page.locator('#a-import-entries img,#a-import-entries svg').count(),0);assert.deepEqual(hits(),[]);
 await page.locator('#a-import-entries button').first().click();await page.locator('#a-rule-pointer').fill('/marker');await page.locator('#a-rule-value').fill('synthetic-A');await page.locator('#a-negative-path').fill('/known-denial');await page.locator('#a-preview').click();await page.locator('#notice.error').waitFor();assert.equal(await page.locator('#a-run').isEnabled(),false);assert.deepEqual(hits(),[]);noCanaries(await page.locator('#notice').innerText(),'import rejection');
 // Unsupported mapping remains blocked; source bodies are never silently executable.
 const querySlot=entry.secret_slots.find(slot=>slot.kind==='credential_query');const refused=await page.evaluate(async({importId,slot})=>{const response=await fetch('/api/assessment/plan',{method:'POST',headers:{Authorization:'Bearer '+sessionToken,'Content-Type':'application/json'},body:JSON.stringify({import_id:importId,entry_index:0,bindings:{},mappings:{[slot]:{literal:'not-permitted'}}})});return {status:response.status,text:await response.text()};},{importId:imported.import_id,slot:querySlot.id});assert.equal(refused.status,400);assert.deepEqual(hits(),[]);
 await page.locator('[data-step="import"]').click();const safeHar={log:{version:'1.2',entries:[{request:{method:'GET',url:info.target+'/invoice/A',headers:[{name:'Authorization',value:'Bearer '+canaries.header}]},response:{status:403,content:{text:canaries.response}}}]}};await page.locator('#a-import-file').setInputFiles({name:'controlled.har',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(safeHar))});await page.waitForFunction(()=>assessment.imported?.entries[0]?.path==='/invoice/A');await page.locator('#a-import-entries button').first().click();await page.locator('#a-title').fill(hostile);await page.locator('#a-owner-secret').fill('Bearer '+canaries.owner);await page.locator('#a-actor-secret').fill('Bearer '+canaries.peer);await page.locator('#a-preview').click();await page.locator('#a-plan-card:not([hidden])').waitFor();assert.deepEqual(hits(),[]);assert.equal(await page.locator('#a-owner-secret').inputValue(),'');assert.equal(await page.locator('#a-actor-secret').inputValue(),'');noCanaries(await page.content(),'preview DOM');
 await page.locator('#a-authorized').check();const dispatched=page.waitForResponse(response=>response.url().endsWith('/api/assessment/run'));await page.locator('#a-run').click();await dispatched;await page.waitForFunction(()=>assessment.current?.value.findings[0]?.status==='confirmed'&&!assessment.job);await page.locator('#a-findings button').first().click();await page.waitForFunction(()=>document.getElementById('a-inspector-title').textContent.startsWith('<img'));assert.equal(await page.locator('#a-inspector-title img,#a-context-title img').count(),0);assert.equal(await page.evaluate(()=>window.__authzXss),undefined);assert.equal(hits().length,4);noCanaries(await page.content(),'observed DOM');noCanaries(await page.evaluate(()=>assessment.current.value),'execution');assert.equal(await page.evaluate(()=>JSON.stringify(sessionStorage)+JSON.stringify(localStorage)),'{}{}');assert(!page.url().includes('#'));
 await page.locator('.nav[data-panel="history"]').click();await page.locator('#history-refresh').click();await page.locator('.timeline-run').first().waitFor();assert.match(await page.locator('.timeline-run').first().innerText(),/<img/);assert.equal(await page.locator('#history-timeline img').count(),0);noCanaries(await page.evaluate(async()=>await api('/api/history')),'history response');
 await page.locator('.nav[data-panel="assessment"]').click();await page.locator('[data-step="handover"]').click();await page.locator('#a-summary').fill(hostile);await page.locator('#a-freeze').click();await page.locator('#a-json:enabled').waitFor();for(const format of ['json','html','pdf']){const pending=page.waitForEvent('download');await page.locator('#a-'+format).click();await (await pending).saveAs(path.join(out,'security-assessment.'+format));}
 const exportedJson=fs.readFileSync(path.join(out,'security-assessment.json'),'utf8'),exportedHtml=fs.readFileSync(path.join(out,'security-assessment.html'),'utf8');noCanaries(exportedJson,'JSON export');noCanaries(exportedHtml,'HTML export');assert(exportedHtml.includes('&lt;img'));assert(!exportedHtml.includes('<img src=x'));
 const exportedPage=await context.newPage();let exportRequests=[];exportedPage.on('request',request=>{if(!request.url().startsWith('file:'))exportRequests.push(request.url());});await exportedPage.goto('file://'+path.join(out,'security-assessment.html'));assert.equal(await exportedPage.evaluate(()=>window.__authzXss),undefined);assert.equal(await exportedPage.locator('[onerror],svg').count(),0);assert.deepEqual(exportRequests,[]);await exportedPage.close();
 // Scan decompressed PDF text and SQLite pages as well as HTTP/log surfaces.
 const scan=spawnSync(process.env.PYTHON||'python3',['-c',`import sys,json\nfrom pathlib import Path\nfrom pypdf import PdfReader\nroot,out=map(Path,sys.argv[1:3]);secrets=json.loads(sys.argv[3]);pdf=''.join(page.extract_text() or '' for page in PdfReader(out/'security-assessment.pdf').pages)\nfor secret in secrets:\n assert secret not in pdf\n for item in root.glob('history.sqlite*'):\n  assert secret.encode() not in item.read_bytes()\nprint('PDF text and durable history contain no canaries')`,temp,out,JSON.stringify(Object.values(canaries))],{cwd:work,encoding:'utf8'});assert.equal(scan.status,0,scan.stdout+scan.stderr);noCanaries(apiResponses,'API responses');noCanaries(stderr,'server stderr');noCanaries(stdout,'server stdout');assert.deepEqual(errors,[]);await page.screenshot({path:path.join(out,'escaped-assessment.png'),fullPage:true});
 fs.writeFileSync(path.join(out,'acceptance.json'),JSON.stringify({passed:true,gates:['F01-05','F01-07','F06-09','F06-10'],request_count:4,no_requests_before_authorization:true,credential_canary_locations:['header','cookie','query','JSON body','response body','error text','runtime owner credential','runtime peer credential'],checked_surfaces:['import API','rendered DOM','execution API','history API','SQLite and WAL bytes','JSON export','HTML export in actual browser','decompressed PDF text','API errors','stdout/stderr','sessionStorage/localStorage','URL after session initialization'],xss_executed:false,page_errors:errors},null,2));console.log('Assessment browser security corpus passed.');
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(async()=>{if(browser)await browser.close();if(server)server.kill('SIGTERM');});
