"use strict";
// Page-local state only. Neither credentials nor evidence are written to browser storage.
const assessment = {imported:null,importId:null,entryIndex:null,review:null,plan:null,job:null,executions:[],selected:null,comparison:null,snapshot:null,signing:false,view:"matrix",traceIds:[],annotations:{},revision:0};
function assessmentStep(name){panel("assessment");if(!$("notice").classList.contains("error"))$("notice").hidden=true;window.scrollTo({top:0,behavior:"instant"});document.querySelectorAll('.assessment-step').forEach(node=>node.classList.toggle('active',node.id==='a-'+name));document.querySelectorAll('[data-step]').forEach(node=>node.classList.toggle('selected',node.dataset.step===name));}
document.querySelectorAll('[data-step]').forEach(button=>button.onclick=()=>assessmentStep(button.dataset.step));
function aInspect(title,subtitle,fields){$('a-inspector-title').textContent=title;$('a-inspector-subtitle').textContent=subtitle;const dl=$('a-inspector-fields');dl.replaceChildren();for(const [name,value] of Object.entries(fields))dl.append(element('dt',name),element('dd',typeof value==='string'?value:pretty(value)));}
function aContext(){ $('a-context-title').textContent=$('a-title').value||'Untitled assessment';$('a-context-origin').textContent=$('a-target').value||'No target selected';$('a-context-count').textContent=assessment.executions.length+' execution'+(assessment.executions.length===1?'':'s');}
function aInvalidate(){assessment.revision++;assessment.review=null;$('a-authorized').checked=false;$('a-run').disabled=true;$('a-plan-card').hidden=true;aContext();}
$('a-contrast').querySelectorAll('input,select').forEach(input=>{if(input.id!=='a-authorized')input.addEventListener('input',aInvalidate);});
$('a-import-file').onchange=guarded(async()=>{const file=$('a-import-file').files[0];if(!file)return;if(file.size>3*1024*1024)throw Error('Choose an export smaller than 3 MiB.');let text=await file.text();$('a-import-file').value='';const imported=await api('/api/assessment/import',{text,profile:$('a-profile').value});text='';assessment.imported=imported.import;assessment.importId=imported.import_id;assessment.entryIndex=null;aInvalidate();const summary=$('a-import-summary');summary.className='callout';summary.textContent=imported.import.entries.length+' requests imported offline · '+imported.import.format_profile+' · secrets removed before retention';$('a-import-entries').replaceChildren();for(const [index,entry] of imported.import.entries.entries()){const button=element('button',undefined,'assessment-row'),details=element('div');details.append(element('strong',entry.method+' '+entry.path),element('small',entry.origin+' · '+entry.secret_slots.length+' credential slots · '+entry.gaps.length+' data gaps'));button.append(details,element('span',entry.execution_blockers.length?'Mapping required':'Map request','badge'));button.onclick=()=>{assessment.entryIndex=index;$('a-target').value=entry.origin;const hasCookie=entry.secret_slots.some(slot=>/cookie/i.test(slot.location)),hasAuth=entry.secret_slots.some(slot=>/authorization/i.test(slot.location));$('a-credential-header').value=hasCookie&&!hasAuth?'Cookie':'Authorization';$('a-request-label').textContent=entry.method+' '+entry.path;$('a-preview').disabled=false;aImportMappings(entry);aInvalidate();aInspect(entry.method+' '+entry.path,'Imported source · request not executed',{Source:entry.source_refs,Secrets:entry.secret_slots,'Data gaps':entry.gaps.length?entry.gaps:'None declared',Blockers:entry.execution_blockers.length?entry.execution_blockers:'None',Observation:'Imported responses are source material, not verified findings.'});assessmentStep('contrast');};$('a-import-entries').append(button);}notify('Offline import complete. Choose a request and define its rule.');});
function aBindings(){const owner=$('a-owner').value.trim(),actor=$('a-actor').value.trim();if(!owner||!actor||owner===actor)throw Error('Choose two distinct identity names.');return {id:'assessment-experiment',title:$('a-title').value.trim(),target:$('a-target').value.trim(),identities:{[owner]:{headers:{[$('a-credential-header').value]:{env:$('a-owner-ref').value.trim()}}},[actor]:{headers:{[$('a-credential-header').value]:{env:$('a-actor-ref').value.trim()}}}},owner_identity:owner,actor_identity:actor,identity_probe:{path:$('a-identity-path').value.trim(),expect:{status:[200],json:{[$('a-identity-pointer').value.trim()]:$('a-identity-value').value}}},negative_probe:{path:$('a-negative-path').value.trim(),expect:{status:$('a-negative-status').value.split(',').map(s=>Number(s.trim())),json_absent:[$('a-rule-pointer').value.trim()]}},rule:{id:'protected-content-boundary',kind:'forbid_field_equal',pointer:$('a-rule-pointer').value.trim(),value:$('a-rule-value').value,resource_id:$('a-resource').value.trim()},capture_mode:$('a-capture').value,omitted_secret_slots:[...$('a-import-mappings').querySelectorAll('[data-header-slot]:checked')].map(input=>input.dataset.headerSlot)};}
async function aCredentials(){for(const role of ['owner','actor']){const input=$('a-'+role+'-secret'),value=input.value;input.value='';if(value)await api('/api/assessment/credentials',{env:$('a-'+role+'-ref').value.trim(),value,identity:$('a-'+role).value.trim(),target_origin:$('a-target').value.trim()});}}
function aPresentPlan(result,kind='experiment'){assessment.plan=result.plan;assessment.review=result.review;assessment.kind=kind;$('a-authorized').checked=false;$('a-run').disabled=true;$('a-plan-card').hidden=false;const contract=result.plan.contract||result.plan.spec?.contract||result.plan.workflow_plan?.spec?.contract||result.plan.execution?.contract;const cases=contract?.cases||[];$('a-plan-budget').textContent=(result.plan.max_requests||result.plan.spec?.max_requests_total||result.plan.request_upper_bound||cases.length)+' request budget';$('a-plan-rows').replaceChildren();for(const c of cases){const row=element('div',undefined,'assessment-row'),text=element('div');text.append(element('strong',c.method+' '+c.path),element('small',c.id+' · '+c.identity+' · controls: '+(c.requires?.join(', ')||'none')));row.append(text);$('a-plan-rows').append(row);}if(kind==='workflow-assurance')$('a-plan-rows').append(element('p',result.plan.spec.max_cycles+' maximum cycles · '+result.plan.cycle_request_upper_bound+' requests per cycle · '+result.plan.cleanup_reserve+' cleanup requests reserved · '+(result.history_storage==='persistent'?'Durable history':'Session-only history: lost when Studio closes')+' · Stop on violation or uncertainty.','subtle'));if(!cases.length)$('a-plan-rows').append(element('pre',pretty(result.plan),'assessment-plan-json'));$('a-plan-hash').textContent='Plan · '+(result.plan.plan_digest||result.plan.experiment_digest||result.plan.plan_sha256||'Bound to this session review');assessmentStep('contrast');$('a-plan-card').scrollIntoView({block:'nearest'});aInspect('Reviewed '+kind,'No target requests sent during preview',{Target:contract?.target||$('a-target').value,'Request budget':$('a-plan-budget').textContent,'Plan digest':$('a-plan-hash').textContent,Controls:'Every prerequisite remains in the reviewed plan',Authorization:'Waiting for your explicit approval','Data gaps':'The preview does not establish execution truth.'});}
$('a-preview').onclick=guarded(async()=>{if(assessment.entryIndex===null)throw Error('Import and select a request first.');await aCredentials();await aPreviewService('/api/assessment/plan',{import_id:assessment.importId,entry_index:assessment.entryIndex,bindings:aBindings(),mappings:aMappings()});});
$('a-authorized').onchange=()=>{$('a-run').disabled=!assessment.review||!$('a-authorized').checked||!!assessment.job;};
function aSetBusy(running){$('a-run').disabled=true;$('a-preview').disabled=running||assessment.entryIndex===null;$('a-cancel').hidden=!running;$('a-job-state').textContent=running?'Executing only the reviewed requests. Controls are evaluated before findings.':$('a-job-state').textContent;}
async function aWatch(job){assessment.job=job.id;aSetBusy(true);$('a-reconnect').hidden=true;assessmentStep('investigate');try{while(assessment.job){const result=await api('/api/jobs/'+job.id);if(result.state==='complete'){assessment.job=null;aSetBusy(false);if($('notice').textContent.includes('fetch'))$('notice').hidden=true;$('a-job-state').textContent=result.cancelled?'Execution ended after cancellation. Inspect incomplete observations.':'Execution complete · scope and controls remain attached to every claim.';if(result.execution){assessment.executions.push({id:result.execution_id,value:result.execution});assessment.current=assessment.executions.at(-1);aRestoreContext(result.execution);assessment.comparison=result.comparison_envelope||null;assessment.findingComparison=result.finding_comparison||null;aRenderFindings();aContext();$('a-freeze').disabled=false;$('a-handover-open').disabled=false;if(assessment.comparison){$('a-retest-result').replaceChildren();for(const transition of aRetestTransitions())$('a-retest-result').append(element('div',transition.case_id+' · '+aRetestText(transition,assessment.comparison),'assessment-row'));}}else if(result.trace){assessment.traceIds.push(result.trace_id);const workflow=result.kind.startsWith('workflow');const destination=workflow?'a-workflow-result':'a-reduction-result';$('a-freeze').disabled=false;aRenderTrace(destination,result.trace);assessmentStep(workflow?'workflow':'reduce');aInspect(result.kind+' evidence','Verified trace from the shared service',{'Result':result.trace.status||result.trace.interpretation||(result.trace.one_minimal?'1-minimal within approved units':result.trace.stop_reason)||'Inspect trace','Digest':result.trace.workflow_digest||result.trace.reduction_digest||result.trace.assurance_digest,'Budget':result.trace.budget_ledger||'See trace','Limitations':result.trace.limitations||'Only this bounded execution was observed.'});}break;}if(result.state==='error'||result.state==='cancelled'){assessment.job=null;aSetBusy(false);throw Error(result.error||'Execution cancelled before evidence was complete.');}await new Promise(resolve=>setTimeout(resolve,350));}}catch(error){if(assessment.job){$('a-reconnect').hidden=false;$('a-job-state').textContent='Connection interrupted. Reconnect to this same job; do not start it again.';}throw error;}}
$('a-run').onclick=guarded(async()=>{const job=await api('/api/assessment/run',{review:assessment.review,authorized:$('a-authorized').checked});await aWatch(job);});
$('a-reconnect').onclick=guarded(async()=>{if(assessment.job)await aWatch({id:assessment.job});});
$('a-cancel').onclick=guarded(async()=>{await api('/api/cancel',{id:assessment.job});$('a-job-state').textContent='Cancellation requested. No further ordinary requests may be dispatched.';});
async function aSelectFinding(index){assessment.selected=index;aRenderFindings();const selectedExecution=assessment.current;const f=selectedExecution.value.findings[index];if(!f)return;$('a-reduce-open').disabled=f.status!=='confirmed';$('a-retest').disabled=false;aLoadAnnotation(f);$('a-change-id').value=f.case_id;try{const data=await api('/api/assessment/inspect',{execution_id:selectedExecution.id,finding_id:f.id});if(assessment.current!==selectedExecution||assessment.selected!==index)return;aInspect(data.finding.title||f.case_id,'Rule → controls → observation',{Rule:data.rule.id+' · '+data.rule.kind+' · '+data.rule.pointer+'\n'+f.rule_digest,'Identity / resource':f.identity+' / '+f.resource_id,Controls:data.controls.map(c=>c.id+' · '+c.outcome).join('\n'),Observation:data.finding.interpretation+' · '+data.finding.status,Evidence:data.finding.evidence_refs,Uncertainty:data.observations.flatMap(o=>o.limitations||[]).join('\n')||'The result applies only to this execution and configured invariant.','Retest coverage':assessment.comparison?aRetestText((assessment.findingComparison?.transitions||assessment.comparison.transitions).find(t=>t.case_id===f.case_id),assessment.comparison):'Not retested','Evidence root':data.report_root});}catch(error){aInspect('Inspector unavailable','Verified server evidence is required',{Reason:error.message});notify(error.message,true);}}

function aRenderFindings(){const value=assessment.current?.value;if(!value)return;$('a-findings').replaceChildren();$('a-graph').replaceChildren();value.findings.forEach((f,index)=>{const selected=assessment.selected===index,row=element('button',undefined,'assessment-row'+(selected?' selected':'')),detail=element('div');detail.append(element('strong',f.case_id),element('small',f.identity+' → '+f.resource_id+' · '+f.interpretation));row.append(detail,element('span',f.status,'badge '+(f.status==='confirmed'?'fail':f.interpretation==='inconclusive'?'inconclusive':'pass')));row.onclick=()=>aSelectFinding(index);$('a-findings').append(row);const node=element('button',undefined,'assessment-graph-node'+(selected?' selected':''));node.append(element('strong',f.identity+' → '+f.resource_id),element('span','Intended: deny protected marker'),element('span','Policy: unknown unless separately supplied'),element('span','Observed: '+f.interpretation+' · '+f.status),element('span','Controls → '+(f.control_refs||[]).map(c=>typeof c==='string'?c:c.case_id||c.id||'control').join(' · ')));node.onclick=()=>aSelectFinding(index);$('a-graph').append(node);});if(assessment.selected===null&&value.findings.length)aSelectFinding(0);}
$('a-view-matrix').onclick=()=>{assessment.view='matrix';$('a-findings').hidden=false;$('a-graph').hidden=true;};$('a-view-graph').onclick=()=>{assessment.view='graph';$('a-findings').hidden=true;$('a-graph').hidden=false;};
$('a-retest').onclick=guarded(async()=>{aInvalidate();const finding=assessment.current.value.findings[assessment.selected];await aPreviewService('/api/assessment/retest',{execution_id:assessment.current.id,selected_ids:[finding.case_id]});});
$('a-reduce-open').onclick=guarded(async()=>{const data=await api('/api/assessment/reduction/units',{execution_id:assessment.current.id});assessment.units=data.units;$('a-reduction-units').replaceChildren();for(const [index,unit] of data.units.entries()){const label=element('label',undefined,'assessment-row'),input=element('input');input.type='checkbox';input.value=index;input.checked=true;label.append(input,element('span',unit.kind+' · '+(unit.name||unit.pointer)+' · '+unit.case_id));$('a-reduction-units').append(label);}if(!data.units.length)$('a-reduction-units').textContent='No permitted removable units. The request is already within the supported reduction surface.';$('a-reduction-preview').disabled=!data.units.length;assessmentStep('reduce');});
$('a-reduction-preview').onclick=guarded(async()=>{aInvalidate();const units=[...$('a-reduction-units').querySelectorAll('input:checked')].map(i=>assessment.units[Number(i.value)]);await aPreviewService('/api/assessment/reduction/plan',{execution_id:assessment.current.id,units,max_requests:Number($('a-reduction-budget').value)},'reduction');});
$('a-handover-open').onclick=()=>assessmentStep('handover');
$('a-freeze').onclick=guarded(async()=>{const result=await api('/api/assessment/freeze',{execution_ids:assessment.executions.map(e=>e.id),comparisons:assessment.findingComparison?[assessment.findingComparison]:assessment.comparison?[assessment.comparison]:[],trace_ids:assessment.traceIds,metadata:aReportMetadata()});assessment.snapshot=result.assessment_id;$('a-assessment-anchor').textContent='Frozen assessment · '+(result.assessment.assessment_digest||result.assessment.snapshot_digest||result.assessment.assessment_sha256);for(const kind of ['json','html','pdf'])$('a-'+kind).disabled=false;$('a-proof').disabled=!assessment.signing;notify('Assessment frozen. Every format is derived from this same snapshot.');});
for(const format of ['json','html','pdf'])$('a-'+format).onclick=guarded(async()=>download(await api('/api/assessment/export',{assessment_id:assessment.snapshot,format},true),'authzledger-assessment.'+format));
$('a-signing').onclick=guarded(async()=>{const data=await api('/api/assessment/signing',{create_session_key:true});assessment.signing=true;$('a-signing-status').textContent=data.message;$('a-proof').disabled=!assessment.snapshot;download(data.public_key,'authzledger-verification-key.pem','application/x-pem-file');});
$('a-proof').onclick=guarded(async()=>download(await api('/api/assessment/proof',{assessment_id:assessment.snapshot},true),'authzledger-assessment-proof.zip'));
const commands=[['Import requests',()=>assessmentStep('import')],['Contrast Lab',()=>assessmentStep('contrast')],['Investigate evidence',()=>assessmentStep('investigate')],['Minimal Reproducer',()=>assessmentStep('reduce')],['Assessment reports & proof',()=>assessmentStep('handover')],['Workflow Contracts',()=>assessmentStep('workflow')],['Living Authorization Graph',()=>panel('intelligence')],['Access matrix',()=>panel('matrix')],['Run history',()=>panel('history')]];let paletteFocus=null;
function aCommands(){const query=$('a-command-search').value.toLowerCase();$('a-command-results').replaceChildren();for(const [label,action] of commands.filter(([label])=>label.toLowerCase().includes(query))){const button=element('button',label);button.onclick=()=>{$('a-palette').close();action();};$('a-command-results').append(button);}}
function aOpenPalette(){paletteFocus=document.activeElement;$('a-command-search').value='';aCommands();$('a-palette').showModal();$('a-command-search').focus();}
$('a-palette-open').onclick=aOpenPalette;$('a-command-search').oninput=aCommands;$('a-palette').addEventListener('close',()=>paletteFocus?.focus());
document.addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();if($('a-palette').open)$('a-palette').close();else aOpenPalette();}});
$('a-palette').addEventListener('keydown',event=>{const buttons=[...$('a-command-results').querySelectorAll('button')],index=buttons.indexOf(document.activeElement);if(event.key==='ArrowDown'||event.key==='ArrowUp'){event.preventDefault();buttons[(index+(event.key==='ArrowDown'?1:-1)+buttons.length)%buttons.length]?.focus();}if(event.key==='Enter'&&document.activeElement===$('a-command-search')){event.preventDefault();buttons[0]?.click();}});
api('/api/session').then(session=>{assessment.signing=session.signed_proof;if(session.signed_proof)$('a-signing-status').textContent='Configured server signing key is ready.';aRecovery(session.assessment_jobs||[]);}).catch(()=>{});
const workflowRows=[];
function aWorkflowRow(role,method,path,status,expected=''){const row={role,method,path,status,expected};workflowRows.push(row);aRenderWorkflow();}
function aRenderWorkflow(){$('a-workflow-steps').replaceChildren();workflowRows.forEach((row,index)=>{const node=element('div',undefined,'workflow-step');for(const [key,label] of [['role','Purpose'],['method','Method'],['path','Path'],['status','HTTP'],['expected','Expected JSON object (optional)']]){const field=element('label',label);let input;if(key==='role'){input=element('select');for(const kind of ['control','setup','precondition','step','postcondition','cleanup']){const option=element('option',kind);option.value=kind;input.append(option);}}else input=element('input');input.value=row[key];input.oninput=()=>{row[key]=input.value;};field.append(input);node.append(field);}const remove=element('button','Remove');remove.onclick=()=>{workflowRows.splice(index,1);aRenderWorkflow();};node.append(remove);$('a-workflow-steps').append(node);});}
for(const row of [['control','GET','/me','200','{"/principal":"peer"}'],['setup','POST','/jobs','201',''],['precondition','GET','/jobs/object','200','{"/state":"draft"}'],['step','POST','/jobs/object/complete','200',''],['postcondition','GET','/jobs/object','200',''],['cleanup','DELETE','/jobs/object','204','']])aWorkflowRow(...row);
$('a-workflow-add').onclick=()=>aWorkflowRow('step','POST','/jobs/object/approve','200','');
async function aWorkflowSpec(){const advanced=$('a-workflow-json').value.trim();if(advanced)return strictJSON(advanced);const owner=$('a-owner').value.trim(),actor=$('a-actor').value.trim(),cases=[],roles={control:[],setup:[],precondition:[],step:[],postcondition:[],cleanup:[]};for(const [index,row] of workflowRows.entries()){const id=row.role+'-'+index,expect={status:row.status.split(',').map(s=>Number(s.trim()))};if(row.expected.trim())expect.json=await strictJSON(row.expected);cases.push({id,identity:['setup','cleanup'].includes(row.role)?owner:actor,method:row.method.toUpperCase(),path:row.path,expect});roles[row.role].push({id,case_id:id,bindings:[]});}for(const role of ['setup','precondition','postcondition'])if(roles[role].length!==1)throw Error('Exactly one '+role+' operation is required.');for(const step of [...roles.precondition,...roles.step,...roles.postcondition,...roles.cleanup])step.bindings=[{source_step:roles.setup[0].id,pointer:$('a-workflow-fixture-pointer').value,type:'string',target:{kind:'path_segment',index:Number($('a-workflow-path-index').value)}}];const variant={id:'reviewed-sequence',omit:[],identity_overrides:{},repeat:{}};const choice=$('a-workflow-variant').value;if(choice==='replay'&&roles.step.length)variant.repeat[roles.step.at(-1).id]=2;if(choice==='skip'&&roles.step.length)variant.omit=[roles.step[0].id];return {schema_version:1,kind:'workflow-spec',id:'studio-workflow',title:$('a-workflow-title').value,contract:{version:1,name:$('a-workflow-title').value,target:$('a-target').value,identities:{[owner]:{headers:{[$('a-credential-header').value]:{env:$('a-owner-ref').value}}},[actor]:{headers:{[$('a-credential-header').value]:{env:$('a-actor-ref').value}}}},cases},controls:roles.control.map(s=>s.case_id),setup:roles.setup[0],precondition:roles.precondition[0],steps:roles.step,postcondition:roles.postcondition[0],cleanup:roles.cleanup,fixture:{source_step:roles.setup[0].id,pointer:$('a-workflow-fixture-pointer').value,type:'string',read_pointer:$('a-workflow-fixture-pointer').value},rule:{id:'forbidden-transition',kind:'forbidden_state',pointer:$('a-workflow-state-pointer').value,value:$('a-workflow-state-value').value},variants:[variant],mutation_approval:cases.filter(c=>!['GET','HEAD','OPTIONS'].includes(c.method)).map(c=>c.id)};}
$('a-workflow').addEventListener('input',aInvalidate);
$('a-workflow-preview').onclick=guarded(async()=>{aInvalidate();await aCredentials();const workflow=await aWorkflowSpec(),cycles=Number($('a-workflow-cycles').value);if(cycles>1){const spec={schema_version:1,kind:'workflow-assurance-spec',workflow,max_cycles:cycles,interval_seconds:Number($('a-workflow-interval').value),max_requests_total:Number($('a-workflow-budget').value),max_history_age_seconds:Number($('a-workflow-history-age').value)};await aPreviewService('/api/assessment/workflow-assurance/plan',{spec},'workflow-assurance');}else await aPreviewService('/api/assessment/workflow/plan',{spec:workflow},'workflow');});
$('a-workflow-file').onchange=guarded(async()=>{$('a-workflow-json').value=pretty(await readFile($('a-workflow-file')));notify('Workflow loaded. Preview its exact scope before execution.');});
function aImportMappings(entry){const node=$('a-import-mappings');node.replaceChildren();for(const slot of entry.secret_slots){if(/authorization|cookie/i.test(slot.location))continue;const row=element('div',undefined,'assessment-row'),label=element('label',slot.location+' · '+slot.kind);if(slot.kind==='header'){const input=element('input');input.type='checkbox';input.dataset.headerSlot=slot.id;label.append(input,document.createTextNode(' Explicitly omit this imported header'));}else{const input=element('input');input.dataset.mappingSlot=slot.id;input.placeholder='Explicit public replacement value';const omit=element('input');omit.type='checkbox';omit.dataset.mappingOmit=slot.id;label.append(input,omit,document.createTextNode(' Omit this field'));}row.append(label);node.append(row);}}
function aMappings(){const output={};for(const input of $('a-import-mappings').querySelectorAll('[data-mapping-slot]')){const omit=[...$('a-import-mappings').querySelectorAll('[data-mapping-omit]')].find(check=>check.dataset.mappingOmit===input.dataset.mappingSlot);if(omit.checked)output[input.dataset.mappingSlot]={omit:true};else if(input.value)output[input.dataset.mappingSlot]={literal:input.value};}return output;}
function aRenderTrace(destination,trace){const target=$(destination),container=element('div',undefined,'assessment-trace');target.replaceChildren(container);if(trace.kind==='workflow-assurance-result'){container.append(element('h3','Bounded workflow assurance · '+trace.status),element('p',trace.completed_cycles+' completed cycles · '+trace.budget_ledger.dispatched_total+' requests · '+trace.stop_reason,'subtle'));for(const cycle of trace.cycles){const row=element('div',undefined,'assessment-row'),detail=element('div');detail.append(element('strong','Cycle '+cycle.cycle+' · '+cycle.status),element('small',cycle.stop_reason||'All reviewed controls and cleanup satisfied'),element('small','History anchor: '+(cycle.history?.record_sha256||'Not retained')));for(const variant of cycle.trace.variants||[])detail.append(element('small',variant.id+' · '+variant.interpretation+' · controls '+(variant.controls_valid?'valid':'invalid')+' · cleanup '+variant.cleanup));row.append(detail);container.append(row);}}else if(trace.kind==='reduction-trace'){container.append(element('h3',trace.one_minimal?'1-minimal within the approved units':'Reduced · minimality not confirmed'),element('p',(trace.accepted_removed?.length||0)+' accepted removals · '+trace.requests_used+' requests · '+trace.stop_reason,'subtle'));for(const attempt of trace.attempts||[]){const row=element('div',undefined,'assessment-row');row.append(element('span',attempt.status||attempt.result||attempt.interpretation||'Candidate checked'),element('small',attempt.phase||'bounded trial'));container.append(row);}}else{for(const variant of trace.variants||[]){const row=element('div',undefined,'assessment-row'),detail=element('div');detail.append(element('strong',variant.id+' · '+variant.interpretation),element('small','Controls: '+(variant.controls_valid?'valid':'invalid')+' · cleanup: '+variant.cleanup),element('small',variant.reason||''));row.append(detail);container.append(row);}}const save=element('button',trace.kind==='reduction-trace'?'Export reproducer evidence':'Export workflow evidence');save.onclick=()=>download(trace,trace.kind==='reduction-trace'?'authzledger-reproducer.json':'authzledger-workflow.json');container.append(save);const details=element('details'),summary=element('summary','Inspect complete trace'),pre=element('pre',pretty(trace));details.append(summary,pre);container.append(details);}
function aReportMetadata(){const metadata={assessment_id:'local-assessment',title:$('a-title').value,finding_annotations:assessment.annotations};if($('a-reviewer').value.trim())metadata.reviewer=$('a-reviewer').value.trim();if($('a-summary').value.trim())metadata.executive_summary=$('a-summary').value.trim();return metadata;}
function aLoadAnnotation(finding){$('a-annotation-selection').textContent=finding.id+' · '+finding.identity+' → '+finding.resource_id;const annotation=assessment.annotations[finding.id]||{};for(const [key,id] of [['impact','a-impact'],['remediation','a-remediation'],['business_risk','a-business-risk'],['cvss_vector','a-cvss']])$(id).value=annotation[key]||'';const ref=annotation.standard_refs?.[0];$('a-standard').value=ref?ref.standard+'|'+ref.version+'|'+ref.id:'';$('a-standard-rationale').value=ref?.rationale||'';}
$('a-annotation-save').onclick=guarded(async()=>{const finding=assessment.current?.value.findings[assessment.selected];if(!finding)throw Error('Select a finding before writing its impact and remediation.');const annotation={};for(const [key,id] of [['impact','a-impact'],['remediation','a-remediation'],['business_risk','a-business-risk'],['cvss_vector','a-cvss']])if($(id).value.trim())annotation[key]=$(id).value.trim();if($('a-standard').value){const [standard,version,id]=$('a-standard').value.split('|');if(!$('a-standard-rationale').value.trim())throw Error('Explain how the finding evidence relates to the selected standard.');annotation.standard_refs=[{standard,version,id,relation:'related',rationale:$('a-standard-rationale').value.trim(),evidence_refs:finding.evidence_refs}];}assessment.annotations[finding.id]=annotation;assessment.snapshot=null;for(const id of ['a-json','a-html','a-pdf','a-proof'])$(id).disabled=true;notify('Finding annotation saved. Freeze a new assessment to include it.');});
api('/api/assessment/catalog',{}).then(catalog=>{for(const [name,standard] of Object.entries(catalog.standards)){for(const id of standard.ids||[]){const option=element('option',name+' '+standard.version+' · '+id);option.value=name+'|'+standard.version+'|'+id;$('a-standard').append(option);}}}).catch(()=>{});
$('a-impact-preview').onclick=guarded(async()=>{if(!assessment.current)throw Error('Run an experiment before planning its impacted retest.');aInvalidate();const changes=[{kind:$('a-change-kind').value,id:$('a-change-id').value.trim(),before_digest:$('a-change-before').value.trim()||null,after_digest:$('a-change-after').value.trim()||null}],impact_map=$('a-impact-map').value.trim()?await strictJSON($('a-impact-map').value):{};const result=await api('/api/assessment/impact',{execution_id:assessment.current.id,changes,impact_map});$('a-impact-result').replaceChildren();for(const [id,reasons] of Object.entries(result.impact.reasons))$('a-impact-result').append(element('div',id+' · '+reasons.map(reason=>reason.reason_code+' ('+reason.source_refs.join(', ')+')').join('; '),'assessment-row'));if(result.plan){aPresentPlan(result);$('a-plan-rows').append(element('p','Selection cause: '+(result.impact.unknown_dependencies.length?'Unknown dependencies → full approved scope':changes[0].kind+' change')+' · Not retested: '+(result.impact.not_retested_ids.join(', ')||'none'),'subtle'));}else notify('No changed dependency requires another request. All cases remain not_retested.');});

async function aPreviewService(route,body,kind="experiment"){const revision=assessment.revision;const result=await api(route,body);if(assessment.revision!==revision)throw Error("The draft changed during preview. Review its updated scope.");aPresentPlan(result,kind);}
function aRestoreContext(execution){$('a-title').value=execution.plan.spec.title;$('a-target').value=execution.contract.target;$('a-rule-pointer').value=execution.plan.rule.pointer||'';$('a-rule-value').value=execution.plan.rule.value??'';$('a-resource').value=execution.plan.rule.resource_id||'';aContext();}
function aRecovery(jobs){if(!jobs.length)return;const node=$('a-recovery');node.hidden=false;node.replaceChildren(element('h3','Resume retained work'),element('p','Reconnect to an existing job. No request is repeated and no new execution is started.','subtle'));for(const job of jobs){const button=element('button',job.kind+' · '+job.state,'assessment-row');button.dataset.kind=job.kind;button.dataset.jobId=job.id;button.onclick=guarded(async()=>{const result=await api('/api/assessment/recover',{job_id:job.id});if(result.baseline_execution&&!assessment.executions.some(e=>e.id===result.baseline_execution.id))assessment.executions.push(result.baseline_execution);await aWatch(result.job);node.hidden=true;});node.append(button);}}

function aRetestText(transition,envelope){if(!transition)return "Not retested";const historical=envelope.baseline_report.finished_at,current=envelope.current_report.finished_at;return transition.status==="not_retested"?"not_retested · historical evidence: "+historical:transition.status+" · baseline: "+historical+" → retest: "+current;}

function aRetestTransitions(){return (assessment.comparison?.transitions||[]).map(item=>({...item,status:assessment.findingComparison?.transitions.find(finding=>finding.case_id===item.case_id)?.status||item.status}));}
